### ISSUE TITLE
Schedule Definition

### ISSUE THREAD

**Issue by ChakshuGautam** [Samagra-Anamaya/admin#3]
- [ ] Define a map (example - Map a `enumerator` to `location` and `date`)
- [ ] How will they change
- [ ] Is there a quota? What happens if the quota is unfulfilled?

**Comment by tanishk2907** [comment]
##Edited
Assignment logic; 
Only 1 layer of admin at state level
Admin can set deadlines to a GP’s survey 
Each gp id covers every village under it 
Quantum of location would be a village (lgd codes)
An operator id will be unique to a gp
Deadline setting is only for tracking and no correlation with expiry of data

**Comment by tanishk2907** [comment]
- locations are not expected to be reassigned in middle of survey.. if someone else has to replace the designated enumerator, they will share credentials

**Comment by tanishk2907** [comment]
@ChakshuGautam @geeky-abhishek 
There are 50.6k village codes in LGD, whereas Census reports 53.8k. The govt has not given LGD codes to the remaining set of villages. We will have to create dummy codes for them to map.
